"""Model components. Importing this package populates the registries."""

from .backbones import BasicBlock, Bottleneck, ResLayer, ResNet, SwinTransformer
from .builder import (
    AGGREGATORS,
    BACKBONES,
    DETECTORS,
    HEADS,
    LOSSES,
    MEMORY,
    MODELS,
    NECKS,
    ROI_EXTRACTORS,
    SHARED_HEADS,
    build_aggregator,
    build_backbone,
    build_detector,
    build_head,
    build_loss,
    build_memory,
    build_neck,
    build_roi_extractor,
    build_shared_head,
)
from .necks import FPN, ChannelMapper

__all__ = [
    "MODELS",
    "BACKBONES",
    "NECKS",
    "ROI_EXTRACTORS",
    "SHARED_HEADS",
    "HEADS",
    "LOSSES",
    "DETECTORS",
    "AGGREGATORS",
    "MEMORY",
    "build_backbone",
    "build_neck",
    "build_roi_extractor",
    "build_shared_head",
    "build_head",
    "build_loss",
    "build_aggregator",
    "build_memory",
    "build_detector",
    "ResNet",
    "ResLayer",
    "BasicBlock",
    "Bottleneck",
    "SwinTransformer",
    "ChannelMapper",
    "FPN",
]
