"""Model components. Importing this package populates the registries."""

from .backbones import BasicBlock, Bottleneck, ResLayer, ResNet, SwinTransformer
from .builder import (
    AGGREGATORS,
    BACKBONES,
    DETECTORS,
    HEADS,
    LOSSES,
    MEMORY,
    MODELS,
    NECKS,
    ROI_EXTRACTORS,
    SHARED_HEADS,
    build_aggregator,
    build_backbone,
    build_detector,
    build_head,
    build_loss,
    build_memory,
    build_neck,
    build_roi_extractor,
    build_shared_head,
)
from .dense_heads import AnchorHead, RPNHead
from .losses import Accuracy, CrossEntropyLoss, L1Loss, SmoothL1Loss, accuracy
from .necks import FPN, ChannelMapper
from .roi_heads import (
    BaseRoIExtractor,
    BBoxHead,
    ConvFCBBoxHead,
    Shared2FCBBoxHead,
    SingleRoIExtractor,
    StandardRoIHead,
)

__all__ = [
    "MODELS",
    "BACKBONES",
    "NECKS",
    "ROI_EXTRACTORS",
    "SHARED_HEADS",
    "HEADS",
    "LOSSES",
    "DETECTORS",
    "AGGREGATORS",
    "MEMORY",
    "build_backbone",
    "build_neck",
    "build_roi_extractor",
    "build_shared_head",
    "build_head",
    "build_loss",
    "build_aggregator",
    "build_memory",
    "build_detector",
    "ResNet",
    "ResLayer",
    "BasicBlock",
    "Bottleneck",
    "SwinTransformer",
    "ChannelMapper",
    "FPN",
    "AnchorHead",
    "RPNHead",
    "BaseRoIExtractor",
    "SingleRoIExtractor",
    "BBoxHead",
    "ConvFCBBoxHead",
    "Shared2FCBBoxHead",
    "StandardRoIHead",
    "CrossEntropyLoss",
    "SmoothL1Loss",
    "L1Loss",
    "Accuracy",
    "accuracy",
]
